language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install --dev

script:
# todo: configure travis
#  - phpunit

notifications:
  email: true
  irc:
    channels:
      - "irc.esper.net#zarthus"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}) %{author}: %{message} - %{build_url}"
  on_failure: always
  on_success: change